# Alaveteli Data
#
# Data-only container to persist a container with alateveli's postgresql and
# postfix data.
#
# VERSION 0.1

FROM busybox
MAINTAINER Vitor Baptista <vitor@vitorbaptista.com>

VOLUME ["/var/lib/postgresql"]

CMD ["/usr/bin/true"]
